#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <memory>
#include <QMainWindow>
#include <QButtonGroup>

class View;
class DataBinding;

namespace Ui {
    class MainWindow;
}

/**
 * @class MainWindow
 *
 * The main graphical user interface class (GUI class) for our application.
 */
class MainWindow : public QMainWindow {
    Q_OBJECT
public:
    MainWindow(QWidget *parent = 0);
    ~MainWindow();

private:
    // Auto-generated by Qt. DO NOT RENAME!
    Ui::MainWindow *ui;
    QList<DataBinding*> m_bindings;
    QList<QButtonGroup*> m_buttonGroups;

    void dataBind();

public slots:

    void settingsChanged();
};

#endif // MAINWINDOW_H
